"""Initial tables

Revision ID: 1215e7ec032f
Revises: 
Create Date: 2026-02-10 11:46:01.357959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1215e7ec032f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_logistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tracking_no', sa.String(length=100), nullable=False, comment='运单号'),
    sa.Column('ref_no', sa.String(length=100), nullable=True, comment='参考号/订单号'),
    sa.Column('logistics_channel', sa.String(length=100), nullable=True, comment='物流渠道'),
    sa.Column('order_status', sa.String(length=50), nullable=True, comment='订单状态'),
    sa.Column('sent_date', sa.Date(), nullable=True, comment='发货日期'),
    sa.Column('destination', sa.String(length=50), nullable=True, comment='目的地'),
    sa.Column('zone', sa.String(length=20), nullable=True, comment='分区'),
    sa.Column('pre_weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='预报重量'),
    sa.Column('actual_weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='实际重量'),
    sa.Column('declared_value', sa.Numeric(precision=12, scale=4), nullable=True, comment='申报价值'),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=4), nullable=True, comment='运费'),
    sa.Column('discount_fee', sa.Numeric(precision=12, scale=4), nullable=True, comment='优惠金额'),
    sa.Column('actual_fee', sa.Numeric(precision=12, scale=4), nullable=True, comment='实收运费'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='支付方式'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_logistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_logistics_ref_no'), ['ref_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_logistics_tracking_no'), ['tracking_no'], unique=True)

    op.create_table('biz_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avg_cost_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('latest_purchase_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_products_sku'), ['sku'], unique=True)

    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sys_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sys_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_sys_users_username'), ['username'], unique=True)

    op.create_table('biz_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform_order_no', sa.String(length=100), nullable=False, comment='平台订单号'),
    sa.Column('order_time', sa.DateTime(), nullable=True, comment='下单时间'),
    sa.Column('buyer_email', sa.String(length=150), nullable=True, comment='买家邮箱'),
    sa.Column('company_name', sa.String(length=150), nullable=True, comment='公司名称'),
    sa.Column('buyer_name', sa.String(length=100), nullable=True, comment='买家姓名'),
    sa.Column('seller_name', sa.String(length=100), nullable=True, comment='卖家账号'),
    sa.Column('product_name', sa.String(length=255), nullable=True, comment='商品名称'),
    sa.Column('sku', sa.String(length=100), nullable=True, comment='SKU'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='数量'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='币种'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='单价'),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=4), nullable=True, comment='订单总额'),
    sa.Column('shipping_fee_income', sa.Numeric(precision=12, scale=4), nullable=True, comment='运费收入'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=4), nullable=True, comment='折扣金额'),
    sa.Column('actual_paid', sa.Numeric(precision=12, scale=4), nullable=True, comment='实付金额'),
    sa.Column('order_status', sa.String(length=50), nullable=True, comment='状态'),
    sa.Column('order_type', sa.String(length=50), nullable=True, comment='订单类型'),
    sa.Column('has_attachment', sa.Boolean(), nullable=True, comment='是否有合同'),
    sa.Column('actual_delivery_time', sa.DateTime(), nullable=True, comment='实际发货时间'),
    sa.Column('buyer_country', sa.String(length=50), nullable=True, comment='买家国家'),
    sa.Column('tax_fee', sa.Numeric(precision=12, scale=4), nullable=True, comment='税费'),
    sa.Column('shipping_address', sa.Text(), nullable=True, comment='收货地址'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='采购成本'),
    sa.Column('logistics_cost', sa.Numeric(precision=12, scale=4), nullable=True, comment='物流支出'),
    sa.Column('profit', sa.Numeric(precision=12, scale=4), nullable=True, comment='毛利'),
    sa.ForeignKeyConstraint(['sku'], ['biz_products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_orders_buyer_email'), ['buyer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_biz_orders_platform_order_no'), ['platform_order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_biz_orders_sku'), ['sku'], unique=False)

    op.create_table('biz_purchases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_no', sa.String(length=100), nullable=False, comment='采购单号'),
    sa.Column('supplier_company', sa.String(length=150), nullable=True, comment='供应商公司'),
    sa.Column('supplier_member', sa.String(length=100), nullable=True, comment='供应商对接人'),
    sa.Column('buyer_company', sa.String(length=150), nullable=True, comment='采购方公司'),
    sa.Column('buyer_member', sa.String(length=100), nullable=True, comment='采购员'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='SKU'),
    sa.Column('product_name', sa.String(length=255), nullable=True, comment='货品标题'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True, comment='采购数量'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True, comment='采购单价'),
    sa.Column('goods_amount', sa.Numeric(precision=12, scale=4), nullable=True, comment='货品总价'),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=4), nullable=True, comment='运费'),
    sa.Column('discount', sa.Numeric(precision=12, scale=4), nullable=True, comment='折扣'),
    sa.Column('actual_payment', sa.Numeric(precision=12, scale=4), nullable=True, comment='实付款'),
    sa.Column('order_status', sa.String(length=50), nullable=True, comment='采购状态'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='付款时间'),
    sa.Column('logistics_company', sa.String(length=100), nullable=True, comment='物流公司'),
    sa.Column('logistics_no', sa.String(length=100), nullable=True, comment='物流单号'),
    sa.Column('receiver_address', sa.Text(), nullable=True, comment='收货地址'),
    sa.ForeignKeyConstraint(['sku'], ['biz_products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biz_purchases_purchase_no'), ['purchase_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_biz_purchases_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_purchases_sku'))
        batch_op.drop_index(batch_op.f('ix_biz_purchases_purchase_no'))

    op.drop_table('biz_purchases')
    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_orders_sku'))
        batch_op.drop_index(batch_op.f('ix_biz_orders_platform_order_no'))
        batch_op.drop_index(batch_op.f('ix_biz_orders_buyer_email'))

    op.drop_table('biz_orders')
    with op.batch_alter_table('sys_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sys_users_username'))
        batch_op.drop_index(batch_op.f('ix_sys_users_phone'))
        batch_op.drop_index(batch_op.f('ix_sys_users_email'))

    op.drop_table('sys_users')
    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_products_sku'))

    op.drop_table('biz_products')
    with op.batch_alter_table('biz_logistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biz_logistics_tracking_no'))
        batch_op.drop_index(batch_op.f('ix_biz_logistics_ref_no'))

    op.drop_table('biz_logistics')
    # ### end Alembic commands ###
