"""Start increasing sku length to 255

Revision ID: 5d754391145e
Revises: 1215e7ec032f
Create Date: 2026-02-10 19:08:18.452369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d754391145e'
down_revision = '1215e7ec032f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_comment='SKU',
               existing_nullable=True)

    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_comment='SKU',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='SKU',
               existing_nullable=False)

    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_comment='SKU',
               existing_nullable=True)

    # ### end Alembic commands ###
