"""Refactor Float to Decimal and add cost fields

Revision ID: 8b86a781c374
Revises: 5d754391145e
Create Date: 2026-02-10 23:29:00.668679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b86a781c374'
down_revision = '5d754391145e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='利润率'))

    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.alter_column('stock_qty',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_comment='采购数量',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biz_purchases', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='采购数量',
               existing_nullable=True)

    with op.batch_alter_table('biz_products', schema=None) as batch_op:
        batch_op.alter_column('stock_qty',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    with op.batch_alter_table('biz_orders', schema=None) as batch_op:
        batch_op.drop_column('profit_rate')

    # ### end Alembic commands ###
